# Generated by Django 3.1 on 2020-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasreceber',
            name='situacao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='descricao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
