# Generated by Django 3.1 on 2020-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
