# Generated by Django 3.1 on 2020-09-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20200923_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
