# Generated by Django 3.1 on 2020-09-23 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20200923_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classificacao_cp', to='webapi.classificacao'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='forma_pagamento_cp', to='webapi.formapagamento'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classificacao_cr', to='webapi.classificacao'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='forma_recebimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='forma_recebimento_cr', to='webapi.formapagamento'),
        ),
    ]
