# Generated by Django 3.1 on 2020-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20200923_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='situacao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
